int Start(void);
int End(void);
void MsgLoad(void);
void LoadAllGraphs(void);
void LoadAllSounds(void);
void SettingsSounds(int, int, int, int);
void SettingsBGMs(int);
void SettingsMEs(int);
void SettingsBGSs(int);
void SettingsSEs(int);
int UpdateKey(void);
void Option(void);
void Menu(void);
void Title(void);
void CharMain(int);
void MoveSupportUP(int);
void MoveSupportDOWN(int);
void MoveSupportLEFT(int);
void MoveSupportRIGHT(int);
void MoveSupportDashUP(int);
void MoveSupportDashDOWN(int);
void MoveSupportDashLEFT(int);
void MoveSupportDashRIGHT(int);
void Move(void);
void MapMove(void);
void Event(void);
void MAPDraw(int, int);
void MAPOverlayDraw(int);
int wall(int, int, int);
int attackup(int, int, int);
int attackdown(int, int, int);
int attackleft(int, int, int);
int attackright(int, int, int);
void StatusSet(void);
void ConfigSave(void);
void ConfigLoad(void);
void Save(void);
void Load(void);